config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'

 resources :items
 get 'items/edit'
 get '/completed' => 'items#completed', as: :completed

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all.order('priority ASC').where(complete: false)
  end

  def new
  	@item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def show
  	@item = Item.find(params[:id])
  end

  def create
  	@item = Item.new(item_params)

  	if @item.save
  		redirect_to items_path
  	else
  		render :new
  	end
  end

  	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to items_path
		else
			render :edit
		end
	end

  def destroy
  	Item.find(params[:id]).destroy
  	redirect_to items_path
  end

  def completed
  	@items = Item.all.order('priority ASC').where(complete: true)
  end

private

def item_params
	params.require(:item).permit(:name, :description, :complete, :priority)
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_shared_index.html.erb
<hr/>
<% @items.each do |item| %>
	<h2><%= item.name %></h2>
	<h3><%= item.description %></h3>
	<h3><%= item.priority %></h3>
	<h3><%= item.complete %></h3>
	<%= link_to 'Show To-Do', item_path(item) %>
	<%= link_to 'Edit To-Do', edit_item_path(item) %>
	<%= link_to 'Delete', item_path(item), method: :delete %>
	<% end %>

app/views/items/completed.html.erb
<h1> Completed Tasks </h1>
<%= render partial: 'shared_index' %>

app/views/items/edit.html.erb
<h1>Edit To-Do</h1>
<%= form_for @item do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %>

	<%= f.label :description %>:
	<%= f.text_field :description %>

	<%= f.label :priority %>:
	<%= f.text_field :priority %>

	<%= f.label :complete %>:
	<%= f.check_box :complete %>

	<%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1> To-Do List </h1>
<%= render partial: 'shared_index' %>

app/views/items/new.html.erb
<h1> New To-Do </h1>
<%= form_for @item do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %>

	<%= f.label :description %>:
	<%= f.text_field :description %>

	<%= f.label :priority %>:
	<%= f.text_field :priority %>

	<%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1> To-Do </h1>
<h2><%= @item.name %></h2>
<h3><%= @item.description %></h3>
<h3><%= @item.priority %></h3>
<h3><%= @item.complete %></h3>
<%= link_to 'Back', items_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'To Do List', items_path %> |
<%= link_to 'Add new To-Do', new_item_path %> |
<%= link_to 'Completed Items', completed_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<hr/>
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to Your To-Do List!</h1>
<p><%= link_to 'View To-Do List', items_path %></p>